### ISSUE TITLE
Tømme preprod, dump fra prod til preprod

### ISSUE THREAD

**Issue by MugunthanD** [navikt/polly#18]
Tømme preprod for data og kjøre inn oppdaterte kodeverk. pluss lage noe testdata. 
Et script for å ta en dump av prod og dytte det inn i preprod. (Nyttig å ha fremover)

**Comment by skotsj** [comment]
Tror ikke det blir så mye script
1 tøm tabeller
```
delete from policy where 1=1;
delete from information_type where 1=1;
delete from process where 1=1;
delete from term where 1=1;
delete from codelist where 1=1;
```
2 bare kjør sql client -> dump data, kjør output sql i preprod
alternativet er nesten å be dba om kjøre full migrering, men det er litt unødvendig

**Comment by skotsj** [comment]
Kan gjøres når som helst, men litt lite data der nå
